name: Release

on:
  push:
    tags:
      - 'v[0-9]+*'

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "stable"
          check-latest: true
      - uses: actions/checkout@v3

      - run: make release
        env:
          CGO_ENABLED: 0

      - uses: TheDoctor0/zip-release@0.7.1
        with:
          path: godot_web*
          filename: godot_web_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            godot_web*.zip
